-- VHDL Entity SCRATCH_LIB.contador_0_99_bloques.symbol
--
-- Created:
--          by - HP.UNKNOWN (LAPTOP-VBR26E3B)
--          at - 22:41:25 29/06/2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY contador_0_99_bloques IS
   PORT( 
      CLK        : IN     STD_LOGIC;
      RST        : IN     STD_LOGIC;
      control_in : IN     std_logic;
      manual_in  : IN     std_logic;
      x_in       : IN     std_logic;
      an         : OUT    std_logic_vector (3 DOWNTO 0);
      dp         : OUT    STD_LOGIC;
      seg        : OUT    std_logic_vector (6 DOWNTO 0)
   );

-- Declarations

END contador_0_99_bloques ;

--
-- VHDL Architecture SCRATCH_LIB.contador_0_99_bloques.struct
--
-- Created:
--          by - HP.UNKNOWN (LAPTOP-VBR26E3B)
--          at - 22:41:25 29/06/2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
USE IEEE.std_logic_unsigned.all;

LIBRARY SCRATCH_LIB;

ARCHITECTURE struct OF contador_0_99_bloques IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL D_out : std_logic_vector(3 DOWNTO 0);
   SIGNAL U_in  : STD_LOGIC_vector(3 DOWNTO 0);


   -- Component Declarations
   COMPONENT cont_0_99
   PORT (
      CLK        : IN     STD_LOGIC;
      RST        : IN     STD_LOGIC;
      control_in : IN     std_logic;
      manual_in  : IN     std_logic;
      x_in       : IN     std_logic;
      D_out      : OUT    std_logic_vector (3 DOWNTO 0);
      U_out      : OUT    std_logic_vector (3 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT multiplex_displays
   PORT (
      CLK  : IN     STD_LOGIC;
      D_in : IN     STD_LOGIC_vector (3 DOWNTO 0);
      RST  : IN     STD_LOGIC;
      U_in : IN     STD_LOGIC_vector (3 DOWNTO 0);
      an   : OUT    std_logic_vector (3 DOWNTO 0);
      dp   : OUT    STD_LOGIC;
      seg  : OUT    std_logic_vector (6 DOWNTO 0)
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : cont_0_99 USE ENTITY SCRATCH_LIB.cont_0_99;
   FOR ALL : multiplex_displays USE ENTITY SCRATCH_LIB.multiplex_displays;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_0 : cont_0_99
      PORT MAP (
         CLK        => CLK,
         RST        => RST,
         control_in => control_in,
         manual_in  => manual_in,
         x_in       => x_in,
         U_out      => U_in,
         D_out      => D_out
      );
   U_1 : multiplex_displays
      PORT MAP (
         CLK  => CLK,
         RST  => RST,
         an   => an,
         dp   => dp,
         U_in => U_in,
         D_in => D_out,
         seg  => seg
      );

END struct;
