-- VHDL Entity SCRATCH_LIB.rs232_rx_tx.symbol
--
-- Created:
--          by - HP.UNKNOWN (LAPTOP-VBR26E3B)
--          at - 12:19:57 19/07/2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY rs232_rx_tx IS
   PORT( 
      CLK     : IN     STD_LOGIC;
      Data    : IN     STD_LOGIC_VECTOR (7 DOWNTO 0);
      H       : IN     STD_LOGIC;
      RST     : IN     STD_LOGIC;
      rx_in   : IN     STD_LOGIC;
      send    : IN     STD_LOGIC;
      Busy_rx : OUT    STD_LOGIC;
      Busy_tx : OUT    STD_LOGIC;
      tx_out  : OUT    STD_LOGIC;
      verif   : OUT    STD_LOGIC_VECTOR (7 DOWNTO 0)
   );

-- Declarations

END rs232_rx_tx ;

--
-- VHDL Architecture SCRATCH_LIB.rs232_rx_tx.struct
--
-- Created:
--          by - HP.UNKNOWN (LAPTOP-VBR26E3B)
--          at - 12:19:57 19/07/2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
USE IEEE.std_logic_unsigned.all;

LIBRARY SCRATCH_LIB;

ARCHITECTURE struct OF rs232_rx_tx IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL B : STD_LOGIC;


   -- Component Declarations
   COMPONENT RX
   PORT (
      B       : IN     STD_LOGIC;
      CLK     : IN     STD_LOGIC;
      RST     : IN     STD_LOGIC;
      rx_in   : IN     STD_LOGIC;
      Busy_rx : OUT    STD_LOGIC;
      verif   : OUT    STD_LOGIC_VECTOR (7 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT TX
   PORT (
      B       : IN     STD_LOGIC;
      CLK     : IN     STD_LOGIC;
      Data    : IN     STD_LOGIC_VECTOR (7 DOWNTO 0);
      RST     : IN     STD_LOGIC;
      send    : IN     STD_LOGIC;
      Busy_tx : OUT    STD_LOGIC;
      tx_out  : OUT    STD_LOGIC
   );
   END COMPONENT;
   COMPONENT base_tiempo
   GENERIC (
      K : integer := 10416;      --constante del comparador
      N : integer := 22          -- numero de bits del contador
   );
   PORT (
      CLK : IN     STD_LOGIC;
      H   : IN     STD_LOGIC;
      RST : IN     STD_LOGIC;
      BT  : OUT    STD_LOGIC
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : RX USE ENTITY SCRATCH_LIB.RX;
   FOR ALL : TX USE ENTITY SCRATCH_LIB.TX;
   FOR ALL : base_tiempo USE ENTITY SCRATCH_LIB.base_tiempo;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_3 : RX
      PORT MAP (
         CLK     => CLK,
         RST     => RST,
         B       => B,
         rx_in   => rx_in,
         verif   => verif,
         Busy_rx => Busy_rx
      );
   U_0 : TX
      PORT MAP (
         CLK     => CLK,
         RST     => RST,
         B       => B,
         send    => send,
         Data    => Data,
         tx_out  => tx_out,
         Busy_tx => Busy_tx
      );
   U_1 : base_tiempo
      GENERIC MAP (
         K => 10416,         --constante del comparador
         N => 24             -- numero de bits del contador
      )
      PORT MAP (
         CLK => CLK,
         RST => RST,
         H   => H,
         BT  => B
      );

END struct;
