-- VHDL Entity SCRATCH_LIB.proyecto_2_bloques.symbol
--
-- Created:
--          by - HP.UNKNOWN (LAPTOP-VBR26E3B)
--          at - 21:45:54 12/07/2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY proyecto_2_bloques IS
   PORT( 
      CLK     : IN     STD_LOGIC;
      H       : IN     STD_LOGIC;
      RST     : IN     STD_LOGIC;
      rx_in   : IN     STD_LOGIC;
      Busy_rx : OUT    STD_LOGIC;
      PWM_d   : OUT    std_logic;
      PWM_i   : OUT    std_logic;
      m_d     : OUT    std_logic_vector (1 DOWNTO 0);
      m_i     : OUT    std_logic_vector (1 DOWNTO 0)
   );

-- Declarations

END proyecto_2_bloques ;

--
-- VHDL Architecture SCRATCH_LIB.proyecto_2_bloques.struct
--
-- Created:
--          by - HP.UNKNOWN (LAPTOP-VBR26E3B)
--          at - 21:45:54 12/07/2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
USE IEEE.std_logic_unsigned.all;

LIBRARY SCRATCH_LIB;

ARCHITECTURE struct OF proyecto_2_bloques IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL BT       : STD_LOGIC;
   SIGNAL verif_in : STD_LOGIC_VECTOR(7 DOWNTO 0);


   -- Component Declarations
   COMPONENT PWM
   PORT (
      CLK   : IN     STD_LOGIC;
      RST   : IN     STD_LOGIC;
      PWM_d : OUT    std_logic;
      PWM_i : OUT    std_logic
   );
   END COMPONENT;
   COMPONENT RX
   PORT (
      B       : IN     STD_LOGIC;
      CLK     : IN     STD_LOGIC;
      RST     : IN     STD_LOGIC;
      rx_in   : IN     STD_LOGIC;
      Busy_rx : OUT    STD_LOGIC;
      verif   : OUT    STD_LOGIC_VECTOR (7 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT base_tiempo
   GENERIC (
      K : integer := 10416;      --constante del comparador
      N : integer := 22          -- numero de bits del contador
   );
   PORT (
      CLK : IN     STD_LOGIC;
      H   : IN     STD_LOGIC;
      RST : IN     STD_LOGIC;
      BT  : OUT    STD_LOGIC
   );
   END COMPONENT;
   COMPONENT control_motor
   PORT (
      CLK      : IN     STD_LOGIC;
      RST      : IN     STD_LOGIC;
      verif_in : IN     STD_LOGIC_VECTOR (7 DOWNTO 0);
      m_d      : OUT    std_logic_vector (1 DOWNTO 0);
      m_i      : OUT    std_logic_vector (1 DOWNTO 0)
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : PWM USE ENTITY SCRATCH_LIB.PWM;
   FOR ALL : RX USE ENTITY SCRATCH_LIB.RX;
   FOR ALL : base_tiempo USE ENTITY SCRATCH_LIB.base_tiempo;
   FOR ALL : control_motor USE ENTITY SCRATCH_LIB.control_motor;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_3 : PWM
      PORT MAP (
         CLK   => CLK,
         RST   => RST,
         PWM_i => PWM_i,
         PWM_d => PWM_d
      );
   U_2 : RX
      PORT MAP (
         CLK     => CLK,
         RST     => RST,
         B       => BT,
         rx_in   => rx_in,
         verif   => verif_in,
         Busy_rx => Busy_rx
      );
   U_0 : base_tiempo
      GENERIC MAP (
         K => 10416,         --constante del comparador
         N => 22             -- numero de bits del contador
      )
      PORT MAP (
         CLK => CLK,
         RST => RST,
         H   => H,
         BT  => BT
      );
   U_1 : control_motor
      PORT MAP (
         verif_in => verif_in,
         CLK      => CLK,
         RST      => RST,
         m_d      => m_d,
         m_i      => m_i
      );

END struct;
